# Pipeline that removes the resources created by the IaC Create Environment pipeline.
pr: none
trigger: none

pool:
  # To use an MS agent:
  # vmImage: ubuntu-latest
  # otherwise, to use your own agent pool:
  name: azure-sprint-pool

variables:
- group: mlops-vg-3

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
    action: 'DeleteRG'
    resourceGroupName: '$(RESOURCE_GROUP)'
    location: $(LOCATION)
  displayName: 'Delete resources in Azure'
